apiVersion: v1
kind: Secret
metadata:
  name: whatsapp-marketing-secrets
  namespace: whatsapp-marketing
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1oZXJl
  REFRESH_TOKEN_SECRET: eW91ci1yZWZyZXNoLXRva2VuLXNlY3JldC1oZXJl
  WHATSAPP_ACCESS_TOKEN: eW91ci13aGF0c2FwcC1hY2Nlc3MtdG9rZW4=
  WHATSAPP_PHONE_NUMBER_ID: eW91ci1waG9uZS1udW1iZXItaWQ=
  WHATSAPP_BUSINESS_ACCOUNT_ID: eW91ci1idXNpbmVzcy1hY2NvdW50LWlk=
  WHATSAPP_WEBHOOK_VERIFY_TOKEN: eW91ci13ZWJob29rLXZlcmlmeS10b2tlbg==
  OPENAI_API_KEY: eW91ci1vcGVuYWktYXBpLWtleQ==
  RAZORPAY_KEY_ID: eW91ci1yYXpvcnBheS1rZXktaWQ=
  RAZORPAY_KEY_SECRET: eW91ci1yYXpvcnBheS1rZXktc2VjcmV0
  STRIPE_SECRET_KEY: eW91ci1zdHJpcGUtc2VjcmV0LWtleQ==
  SMTP_PASS: eW91ci1zbXRwLXBhc3N3b3Jk
  TWILIO_AUTH_TOKEN: eW91ci10d2lsaW8tYXV0aC10b2tlbg==
